version: "3"

services:
  frontend:
    image: al2108/frontend-swarm
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - backend
    networks:
      - backend
    ports:
      - "4000:80"

  backend:
    image: al2108/backend-swarm
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - database
    networks:
      - database
      - backend
    ports:
      - "8080:8080"

  database:
    image: postgres:12.1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.labels.db==postgres
      restart_policy:
        condition: on-failure
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    expose:
      - "5432"
    ports:
      - "5432:5432"

  visualizer:
    image: dockersamples/visualizer:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:8080"

networks:
  database:
  backend:

volumes:
  db-data: