apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt-frontend
  labels:
    app: kt
spec:
  selector:
    matchLabels:
      app: kt
      tier: frontend
  replicas: 5
  template:
    metadata:
      labels:
        app: kt
        tier: frontend
    spec:
      containers:
      - name: kt-frontend
        image: al2108/frontend-swarm:1.3
        ports:
        - containerPort: 80

