{
   "structureVersion": "1.5.0",
   "registrationDate": "2020-02-05T22:37:50+01:00",
   "atom": {
      "url": "http://localhost/api/users",
      "verb": "GET",
      "body": null,
      "headers": "{\n   \"Accept\": \"application/json\",\n   \"Content-Type\": \"application/json; charset=utf-8\"\n}",
      "bodyKind": "json",
      "withCredentials": false
   },
   "scenario": {
      "code": "$.ajax({\n\turl:'https://maps.googleapis.com/maps/api/geocode/json?address=Meran',\n\tmethod:'GET',\n\tsuccess: function(res){\n\t\tdone(res);\n\t},\n\terror: function(err){\n\t\tdone(err);\n}});\n"
   },
   "massive": {
      "batch": "[\n   {\n      \"verb\": \"GET\",\n      \"url\": \"https://maps.googleapis.com/maps/api/geocode/json?address=Meran\",\n      \"body\": null,\n      \"headers\": null,\n      \"withCredentials\": false\n   },\n   {\n      \"verb\": \"GET\",\n      \"url\": \"https://maps.googleapis.com/maps/api/geocode/json?address=Varese\",\n      \"body\": null,\n      \"headers\": null,\n      \"withCredentials\": false\n   },\n   {\n      \"verb\": \"GET\",\n      \"url\": \"https://maps.googleapis.com/maps/api/geocode/json?address=Chennai\",\n      \"body\": null,\n      \"headers\": null,\n      \"withCredentials\": false\n   }\n]"
   },
   "engine": {
      "name": "KT-API",
      "iterations": 1000,
      "delay": 1,
      "warmup": 5,
      "timeout": 30000,
      "mode": "atomAdapter"
   }
}