server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/backend
    username: postgres
    password: postgres

  jpa:
    show-sql: false

    hibernate:
      ddl-auto=create: create

